---
title: "ctSEM ema"
format: html
author: Clara Behnke
---

## Load packages

```{r, message=FALSE}
library(readr)
library(tidyverse)
library(misty)
```

## Data preparation

```{r, message=FALSE}
# Load data
dat_ema <- read_csv("00000000-0000-0007-0000-000000000007.csv")
dat_ema1 <- read_csv("00000000-0000-0003-0000-000000000003.csv")

# exclude non-participants
dat <- bind_rows(
  dat_ema %>% filter(grepl("NBMP", pseudonym, fixed = TRUE)),
  dat_ema1 %>% filter(grepl("NBMT", pseudonym, fixed = TRUE))
)

#str(dat)
#View(dat)

# add columns for every item
dat <- dat %>%
  mutate(
    A1a = as.numeric(ifelse(grepl("A1a", variableName), variableValue, NA)),
    A1b = as.numeric(ifelse(grepl("A1b", variableName), variableValue, NA)),
    A3 = as.numeric(ifelse(grepl("A3", variableName), variableValue, NA)),
    A9 = as.numeric(ifelse(grepl("A9", variableName), variableValue, NA)),
    A4 = as.numeric(ifelse(grepl("A4", variableName), variableValue, NA)),
    K3 = as.numeric(ifelse(grepl("K3", variableName), variableValue, NA)),
    K4 = as.numeric(ifelse(grepl("K4", variableName), variableValue, NA)),
    A8 = as.numeric(ifelse(grepl("A8", variableName), variableValue, NA)),
    K1 = as.numeric(ifelse(grepl("K1", variableName), variableValue, NA)),
    K2 = as.numeric(ifelse(grepl("activity_K2", variableName), variableValue, NA)),
    K2_other = ifelse(grepl("K2_other", variableName), variableValue, NA),
    A6 = as.numeric(ifelse(grepl("A6", variableName), variableValue, NA)),
    A2 = as.numeric(ifelse(grepl("A2", variableName), variableValue, NA)),
    A5 = as.numeric(ifelse(grepl("A5", variableName), variableValue, NA)),
    A7 = as.numeric(ifelse(grepl("A7", variableName), variableValue, NA))
  )

# exclude self initiated interactions
dat_systemTriggered <- dat %>%
  filter(triggerName == "TriggerDailyAtRandomInTimeRangeVariableConfig")

# aggregate to one time point per interaction
items <- c("A1a", "A1b", "A3", "A9", "A4", "K3", "K4", "A8", "K1", "K2", "A6", "A2", "A5", "A7")
act_scores <- c("A1b", "A3", "A4", "A6", "A2", "A5", "A7")
constant_cols <- c("pseudonym", "group", "triggerName", "interactionName", 
                      "interactionReminder", "interactionStatus")

dat_aggregated <- dat_systemTriggered %>%
  group_by(triggerCount, pseudonym) %>%
  summarise(
    # constant columns: should be the same for all rows in group
    group = first(group),
    triggerName = first(triggerName),
    interactionName = first(interactionName),
    interactionReminder = first(interactionReminder),
    interactionStatus = first(interactionStatus),

    # for items: keep the non-NA value (should be only one per group)
    A1a = first(na.omit(A1a)),
    A1b = first(na.omit(A1b)),
    A3 = first(na.omit(A3)),
    A9 = first(na.omit(A9)),
    A4 = first(na.omit(A4)),
    K3 = first(na.omit(K3)),
    K4 = first(na.omit(K4)),
    A8 = first(na.omit(A8)),
    K1 = first(na.omit(K1)),
    K2 = first(na.omit(K2)),
    K2_other = first(na.omit(K2_other)),
    A6 = first(na.omit(A6)),
    A2 = first(na.omit(A2)),
    A5 = first(na.omit(A5)),
    A7 = first(na.omit(A7)),

    # all other cols: keep first value
    across(
      !any_of(c("triggerCount", "pseudonym", constant_cols, items)),
      first
    ),

    .groups = "drop"
  )

# individual time scale in days and hours
dat_aggregated <- dat_aggregated %>%
  
  group_by(pseudonym) %>%
  arrange(variableCreatedDateTime) %>%
  
  # time difference from first observation in days and hours
  mutate(
    time_days = as.numeric(difftime(variableCreatedDateTime, first(variableCreatedDateTime), units = "days"))
  ) %>%
  mutate(
    time_hours = as.numeric(difftime(variableCreatedDateTime, first(variableCreatedDateTime), units = "hours"))
  ) %>%
  mutate(
    K1 = as.factor(K1),
    K2 = as.factor(K2)
  ) %>%
  ungroup() %>%
  
  # sort by pseudonym and time
  arrange(pseudonym, time_days)

write.csv(dat_aggregated, file = "aggregated_data_triggered_ZI.csv", row.names = FALSE)

# Scaling

# dat_scaled <- dat_aggregated
# dat_scaled[, c("A1a", "A1b", "A3", "A9", "A4", "K3", "K4", "A8", "A6", "A2", "A5", "A7")] <- scale(dat_scaled[, c("A1a", "A1b", "A3", "A9", "A4", "K3", "K4", "A8", "A6", "A2", "A5", "A7")])
```

```{r}
# Data cleaning: remove rows that only contain 50s
n_all_50 <- dat_aggregated %>%
  filter(if_all(all_of(act_scores), ~ .x == 50)) 

#dat_aggregated <- dat_aggregated %>%
#  filter(!if_all(all_of(act_scores), ~ .x == 50))
```


## Descriptives

```{r}
# proportion of completed questionnaires
xtabs(~ interactionStatus, data = dat_aggregated)["Completed"]/nrow(dat_aggregated)

# proportion of requested interaction
xtabs(~ triggerName, data = dat)["RequestedInteraction"]/nrow(dat)

```